apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-dep
  labels: 
    app: myapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata: 
      labels:
        app: myapp
    spec:
      containers:
      - name: web
        image: nginx:alpine
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp-dep
  name: webapp-dep
spec:
  ports:
  - nodePort: 32632
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
  type: NodePort