apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: jmevada6/myfirstapp
        ports:
        - containerPort: 8080
# apiVersion: app/V1
# kind: Deployment
# metadata:
#   name: basic-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: basic-app
#   template:
#     metadata:
#       labels:
#         app: basic-app
#     spec:
#       containers:
#       - name: basic-app
#         image: jmevada6/myfirstapp
#         ports:
#         - containerPort: 80
#         env:
#           - name: PORT
#             value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: basic-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: nginx